version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
    interval: daily
    allow:
      - dependency-type: "all"
    groups:
      test:
        patterns:
          - "capybara*"
          - "combustion"
          - "rspec-*"
          - "timecop"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
